Force linking to ncurses
Not doing this breaks some configure tests, like virtuoso's:
configure:33614: checking for -lreadline without -ltermcap
configure:33640: gcc -o conftest -g -O2   conftest.c  -lreadline >&5
/lib64/libreadline.so: undefined reference to `PC'
/lib64/libreadline.so: undefined reference to `tgetflag'
/lib64/libreadline.so: undefined reference to `tgetent'
/lib64/libreadline.so: undefined reference to `UP'
/lib64/libreadline.so: undefined reference to `tputs'
/lib64/libreadline.so: undefined reference to `tgoto'
/lib64/libreadline.so: undefined reference to `tgetnum'
/lib64/libreadline.so: undefined reference to `BC'
/lib64/libreadline.so: undefined reference to `tgetstr'
collect2: ld returned 1 exit status