Fix llvm when gold is disabled
configure expects a pathname for binutils-include or 'default'.

option_with will make it blank, causing the following compilation error:
    configure: error: Invalid path for --with-binutils-include. Provide full path

Also, get rid of broken symlink with -gold.